Fix/improve attempt for playlist page filter options persistsence
OdyseeTeam/odysee-frontend pull request #2531
Opened 2023-02-03 15:16 UTC by keikari

## Fixes 
Issue Number: #2410 

Also supposed to fix/improve these: 
-changing page number cleared sort_type param from url 
-sort_type param in url didn't actually got used  
-sort_type param changes got always persistently stored, even without clicking the check-mark-button
-sort text can now also be passed from url, making last search persist when navigating  to page using back button

2023-02-04 13:36 UTC, keikari commented
Read some stuff, and I think I'm using location wrong, will try to figure more sensible way

2023-02-06 13:54 UTC, toshokanneko requested changes
Seems good except for this one typo. Most likely caused by the auto correction of the editor ;)

2023-02-06 13:54 UTC, toshokanneko commented on ui/component/common/paginate.jsx
> +  shouldResetPageNumber?: Boolean,
=> `boolean` ;)

2023-02-06 13:57 UTC, keikari commented on ui/component/common/paginate.jsx
> +  shouldResetPageNumber?: Boolean,
Fixed!

2023-02-06 13:57 UTC, merged