Channel mentioning rewrite + refactor + add support for suggesting emojis
OdyseeTeam/odysee-frontend pull request #332
Opened 2021-11-19 14:25 UTC by saltrafael

## Fixes

Issue Number: Closes #68 Closes #135

- Created a consts file for Regex
- Moved channel mentioning away from commentCreate
  - now works in any textarea field
 - Added support for suggesting emojis when typing :

## PR Checklist

<details><summary>Toggle...</summary>

What kind of change does this PR introduce?

- [X] Bugfix
- [X] Feature
- [X] Code style update (formatting)
- [X] Refactoring (no functional changes)
- [ ] Documentation changes
- [ ] Other - Please describe:
</details>

2021-11-19 16:34 UTC, dan-peterson commented on ui/component/collectionEdit/view.jsx
> +  let prefix = IS_WEB ? `${DOMAIN}/` : 'lbry://';
Do we still need to check IS_WEB?

2021-11-22 06:29 UTC, infinite-persistence requested changes
## Review Part 1 (~40% done)
Still going through the changes, but thought of passing along the findings first.

<details>
  <summary>Also, some notes for future...</summary>
  
1. Try to keep 1 commit per change, e.g. "moved xxx to yyy", "re-ordered parameters", "consolidate/DRY parseName", "remove desktop code". This makes the delta consumable for review and for future reference when we need to do partial revert.
2. Re-ordered code is the hardest to review. Restrict those into single-commits with "no functional change" in the commit message, so that it'll be easier to review (we can then skim/skip these commits by assuming no new functionality was added). Make functional changes in the next commit instead.
3. I think we should stop re-ordering import lines until we come to a consensus on how it should be ordered (we can start a new thread in Slack).  I believe Sean's ordering was:  constants -> external (React) -> internal; while the one in this PR is a direct line sort.  I think line sorts don't work well because of `{ }`, and we'll end up with unnecessary deltas in the future.
    - e.g.  If we change from `import { blah }` to `import React, { blah }`, it will involve a re-ordering and a less-readable delta.
    - There might be plugins to auto-sort at commit time based on agreed rules (like our linter), so that we aren't fighting each other's style + no need to manually sort.

</details>

2021-11-22 06:29 UTC, infinite-persistence commented on ui/component/commentCreate/view.jsx
>  import * as KEYCODES from 'constants/keycodes';
After typing some comments in livestream, the HOME and END key does not bring the cursor to the start and end of the line.  Reverted the PR, then it'll work.

2021-11-22 06:53 UTC, infinite-persistence requested changes

2021-11-22 06:53 UTC, infinite-persistence commented on ui/component/textareaWithSuggestions/view.jsx
> +  function handleChange(e: SyntheticInputEvent<*>) {
I typed "hello world :angry @" 
On the "@", I was expecting channel suggestions to appear, but it stayed at emote suggestion.

2021-11-22 13:39 UTC, saltrafael commented
`REBASE`

moved out the regex changes which made it too big and out of scope

`DRAFT`

have more changes to do, fix the requested changes

2021-11-22 14:23 UTC, infinite-persistence requested changes

2021-11-22 14:23 UTC, infinite-persistence commented on ui/component/common/form-components/form-field.jsx
> +import TextareaWithSuggestions from 'component/textareaWithSuggestions';
Underscore, for example ":angry_" , dismisses the suggestion popup.  It should still be there since `:angry_1` is a selection.

2021-11-22 14:23 UTC, infinite-persistence commented on ui/component/textareaWithSuggestions/index.js
> +  const claim = makeSelectClaimForUri(props.uri)(state);
Please help to start switching to `selectClaimForUri(state, props.uri)` (note the change in function signature as well).

2021-11-22 14:26 UTC, infinite-persistence commented
> _moved out the regex changes which made it too big and out of scope_
It's ok if you want to leave it there.  I've reviewed the first 3 commits ... only last 2 commits left to review.
The separation note is more for the future :)

2021-12-06 20:45 UTC, saltrafael commented
- Rebased master
- Improved group label to display the matching term (similar to discord)
- Added back support for searching mention
- Added support for typing emojis (it works very similar to slack for comparison)

2021-12-07 02:48 UTC, infinite-persistence requested changes
Initial glance.
Looks smooth.

2021-12-07 02:48 UTC, infinite-persistence commented on ui/component/textareaWithSuggestions/view.jsx
> +    <Autocomplete
After typing `@` in a comment text field.  Just need to put a key for each item in the list.

![image](https://user-images.githubusercontent.com/64950861/144954845-c33d24fc-c383-4d71-b11b-1f523e09dcfe.png)

2021-12-07 02:48 UTC, infinite-persistence commented on ui/component/textareaWithSuggestions/view.jsx
> +      autoHighlight
Also from `@` in the text field:

![image](https://user-images.githubusercontent.com/64950861/144955127-f873e90f-13b0-46c2-9297-131302be80a1.png)

2021-12-07 02:48 UTC, infinite-persistence commented on ui/component/textareaWithSuggestions/view.jsx
> +      loadingText={results || showPlaceholder ? __('Searching...') : __('Nothing found')}
"Searching..." in invisible in dark mode.

![image](https://user-images.githubusercontent.com/64950861/144955244-72e601b5-9393-4b4d-8a3e-7a4c6b709682.png)

2021-12-07 02:48 UTC, infinite-persistence commented on ui/component/textareaWithSuggestions/view.jsx
> +      onBlur={() => onBlur && onBlur()}
In this video, the search results came back, but the gui is stuck at "Searching..."

https://www.notion.so/Temp-Links-31f1387c619d4f338b877c41b99fd59b#b1662ab22da947acbdd79f7350f8a08a

2021-12-07 11:35 UTC, saltrafael commented on ui/component/textareaWithSuggestions/view.jsx
> +          : ''}
good find!

2021-12-07 12:36 UTC, saltrafael commented on package.json
> +    "@mui/material": "^5.2.1",
I had the mui switch explanation saved as draft on slack and forgot to send 😆 ! it is there now for discussion

2021-12-08 15:59 UTC, infinite-persistence approved these changes

2021-12-08 16:00 UTC, infinite-persistence commented
Glanced through latest changes ... LGTM.
Didn't run and try it though.

2021-12-08 18:59 UTC, tzarebczan commented
Yep, seems to be working well with initial testing outside of the livestream comments. Once that's fixed, will ship.

2021-12-09 20:35 UTC, merged