Make Repost a Modal
OdyseeTeam/odysee-frontend pull request #978
Opened 2022-02-27 03:34 UTC by bradley-ray

## Fixes

Issue Number:

## What is the current behavior?
Currently, links to create a repost takes a user to a seperate page.

## What is the new behavior?
Links to create a repost now open a modal. This made more sense considering most other actions are also done through modals. This behavior also exists in the LBRY app.

## Other information

## PR Checklist

<details><summary>Toggle...</summary>

What kind of change does this PR introduce?

- [ ] Bugfix
- [X] Feature
- [ ] Code style update (formatting)
- [ ] Refactoring (no functional changes)
- [ ] Documentation changes
- [ ] Other - Please describe:

Please check all that apply to this PR using "x":

- [X] I have checked that this PR is not a duplicate of an existing PR (open, closed or merged)
- [X] I have checked that this PR does not introduce a breaking change
- [ ] This PR introduces breaking changes and I have provided a detailed explanation below

</details>

2022-02-28 14:08 UTC, infinite-persistence requested changes

2022-02-28 14:08 UTC, infinite-persistence commented on ui/component/fileActions/view.jsx
> +        <Tooltip title={__('Repost this claim')} arrow={false}>
In general, we are avoiding the use of "claim" in Odysee to simplify it from lbry-desktop.
I think the original should be ok?

2022-02-28 14:08 UTC, infinite-persistence commented on ui/component/fileActions/view.jsx
> +            className={'button--file-action'}
The original should be good -- use braces only when necessary.

2022-03-01 15:27 UTC, tzarebczan commented
Waiting on fixes from feedback in https://github.com/lbryio/lbry-desktop/pull/7491 also.

2022-03-03 15:32 UTC, bradley-ray commented on ui/component/channelAbout/view.jsx
> +            {!SIMPLE_SITE && (
I removed it to test something and forgot to add it back.

2022-03-04 05:05 UTC, infinite-persistence commented
- [ ] The removal in the first comment has not been reverted.

2022-03-04 05:06 UTC, infinite-persistence commented on ui/component/fileActions/view.jsx
> +            className={'button--file-action'}
This one hasn't been reverted.

2022-03-04 05:09 UTC, infinite-persistence commented on ui/modal/modalRepost/view.jsx
> +  name: string,
This should be `contentName`.  Lint is failing.

2022-04-12 13:25 UTC, merged